import { Transaction, Subscription, Settlement, BankEntry, ReconciliationFlag, DiscrepancyType } from './types';

export const mockTransactions: Transaction[] = [
  {
    id: 'tx_101',
    date: '2026-08-01',
    merchantName: 'AWS Cloud Services',
    amount: 18450,
    currency: 'INR',
    category: 'Cloud Infrastructure',
    paymentMethod: 'Corporate Card',
    isRecurring: true,
    status: 'SUCCESS',
  },
  {
    id: 'tx_102',
    date: '2026-08-03',
    merchantName: 'Meta Ads',
    amount: 45000,
    currency: 'INR',
    category: 'Digital Marketing',
    paymentMethod: 'Corporate Card',
    isRecurring: false,
    status: 'SUCCESS',
  },
  {
    id: 'tx_103',
    date: '2026-08-05',
    merchantName: 'Slack Technologies',
    amount: 6200,
    currency: 'INR',
    category: 'SaaS & Software',
    paymentMethod: 'Corporate Card',
    isRecurring: true,
    status: 'SUCCESS',
  },
  {
    id: 'tx_104',
    date: '2026-08-10',
    merchantName: 'Figma Subscription',
    amount: 3500,
    currency: 'INR',
    category: 'SaaS & Software',
    paymentMethod: 'Corporate Card',
    isRecurring: true,
    status: 'SUCCESS',
  },
  {
    id: 'tx_105',
    date: '2026-08-12',
    merchantName: 'Delhivery Logistics',
    amount: 28400,
    currency: 'INR',
    category: 'Logistics & Shipping',
    paymentMethod: 'Net Banking',
    isRecurring: false,
    status: 'SUCCESS',
  },
  {
    id: 'tx_106',
    date: '2026-08-15',
    merchantName: 'Notion Labs',
    amount: 1800,
    currency: 'INR',
    category: 'SaaS & Software',
    paymentMethod: 'Corporate Card',
    isRecurring: true,
    status: 'SUCCESS',
  },
  {
    id: 'tx_107',
    date: '2026-08-18',
    merchantName: 'Google Ads',
    amount: 32000,
    currency: 'INR',
    category: 'Digital Marketing',
    paymentMethod: 'Corporate Card',
    isRecurring: false,
    status: 'SUCCESS',
  },
  {
    id: 'tx_108',
    date: '2026-08-20',
    merchantName: 'Razorpay Gateway Fee',
    amount: 4120,
    currency: 'INR',
    category: 'Payment Gateway Fees',
    paymentMethod: 'UPI',
    isRecurring: true,
    status: 'SUCCESS',
  },
];

export const mockSubscriptions: Subscription[] = [
  {
    id: 'sub_01',
    serviceName: 'AWS Cloud Services',
    billingCycle: 'Monthly',
    amount: 18450,
    lastBilledDate: '2026-08-01',
    nextBillingDate: '2026-09-01',
    category: 'Cloud Infrastructure',
    status: 'ACTIVE',
    usageScore: 85,
  },
  {
    id: 'sub_02',
    serviceName: 'Slack Technologies',
    billingCycle: 'Monthly',
    amount: 6200,
    lastBilledDate: '2026-08-05',
    nextBillingDate: '2026-09-05',
    category: 'SaaS & Software',
    status: 'FLAGGED_FOR_REVIEW',
    usageScore: 30, 
  },
  {
    id: 'sub_03',
    serviceName: 'Figma Professional',
    billingCycle: 'Monthly',
    amount: 3500,
    lastBilledDate: '2026-08-10',
    nextBillingDate: '2026-09-10',
    category: 'SaaS & Software',
    status: 'ACTIVE',
    usageScore: 90,
  },
  {
    id: 'sub_04',
    serviceName: 'Zoom Business',
    billingCycle: 'Monthly',
    amount: 2400,
    lastBilledDate: '2026-07-28',
    nextBillingDate: '2026-08-28',
    category: 'SaaS & Software',
    status: 'FLAGGED_FOR_REVIEW',
    usageScore: 12, // Very low usage
  },
];

export const mockSettlements: Settlement[] = [
  {
    settlementId: 'set_801',
    date: '2026-08-05',
    grossAmount: 150000,
    fees: 3000,
    tax: 540,
    netAmount: 146460,
    status: 'SETTLED',
    transactionCount: 42,
  },
  {
    settlementId: 'set_802',
    date: '2026-08-12',
    grossAmount: 220000,
    fees: 4400,
    tax: 792,
    netAmount: 214808,
    status: 'SETTLED',
    transactionCount: 68,
  },
  {
    settlementId: 'set_803',
    date: '2026-08-19',
    grossAmount: 180000,
    fees: 3600,
    tax: 648,
    netAmount: 175752,
    status: 'SETTLED',
    transactionCount: 51,
  },
  {
    settlementId: 'set_804',
    date: '2026-08-26',
    grossAmount: 95000,
    fees: 1900,
    tax: 342,
    netAmount: 92758,
    status: 'SETTLED',
    transactionCount: 29,
  },
];

export const mockBankEntries: BankEntry[] = [
  {
    bankTransactionId: 'bank_tx_01',
    date: '2026-08-05',
    description: 'NEFT-RAZORPAY SOFTWARE PVT LTD-SET801',
    creditAmount: 146460,
    debitAmount: 0,
    balanceAfter: 480200,
    referenceNo: 'REF80100293',
  },
  {
    bankTransactionId: 'bank_tx_02',
    date: '2026-08-12',
    description: 'NEFT-RAZORPAY SOFTWARE PVT LTD-SET802',
    creditAmount: 209808, 
    debitAmount: 0,
    balanceAfter: 690008,
    referenceNo: 'REF80200112',
  },
  {
    bankTransactionId: 'bank_tx_03',
    date: '2026-08-19',
    description: 'NEFT-RAZORPAY SOFTWARE PVT LTD-SET803',
    creditAmount: 175752,
    debitAmount: 0,
    balanceAfter: 865760,
    referenceNo: 'REF80300481',
  },
];

export const mockReconciliationFlags: ReconciliationFlag[] = [
  {
    id: 'flag_01',
    settlementId: 'set_802',
    bankTransactionId: 'bank_tx_02',
    discrepancyType: DiscrepancyType.AMOUNT_MISMATCH,
    expectedAmount: 214808,
    actualAmount: 209808,
    difference: 5000,
    flaggedDate: '2026-08-13',
    aiExplanation:
      'Settlement payout set_802 was credited ₹5,000 short in the bank statement. Likely due to an unadjusted chargeback or temporary bank hold.',
    status: 'UNRESOLVED',
  },
  {
    id: 'flag_02',
    settlementId: 'set_804',
    discrepancyType: DiscrepancyType.MISSING_IN_BANK,
    expectedAmount: 92758,
    actualAmount: 0,
    difference: 92758,
    flaggedDate: '2026-08-27',
    aiExplanation:
      'Settlement set_804 marked as settled by gateway on Aug 26, but no corresponding NEFT credit entry appears in bank statements as of Aug 30.',
    status: 'UNRESOLVED',
  },
];